use wheels;

-- Question 1:
-- Find the total number of customers who have placed orders. What is the distribution of the customers across states?

SELECT 
	state, 
	COUNT(customer_id) AS total_customers
FROM customer_t
GROUP BY 1
ORDER BY 2 DESC;


-- Question 2:
-- Which are the top 5 vehicle makers preferred by the customers?

SELECT 
	vehicle_maker AS top_vehicle_makers, 
	COUNT(customer_id) AS total_customers
FROM product_t JOIN customer_t
GROUP BY top_vehicle_makers
ORDER BY total_customers DESC
LIMIT 5;


-- Question 3:
-- Which is the most preferred vehicle maker in each state?

SELECT *
FROM
(
	SELECT 
		state, 
		vehicle_maker,
		COUNT(customer_id) AS total_customers,
    RANK() OVER (PARTITION BY state ORDER BY COUNT(customer_id) DESC) AS ranking
    FROM product_t 
    JOIN order_t USING(product_id)
    JOIN customer_t USING(customer_id)
	GROUP BY 1, 2 
) AS preferred_vehicle
WHERE ranking = 1
ORDER BY 3 DESC;


-- Question 4:
-- Find the overall average rating given by the customers. What is the average rating in each quarter?

WITH rating AS 
(
	SELECT
		customer_feedback,
		quarter_number,
    CASE
		WHEN customer_feedback = 'very bad' THEN '1'
		WHEN customer_feedback = 'bad' THEN '2'
		WHEN customer_feedback = 'okay' THEN '3'
		WHEN customer_feedback = 'good' THEN '4'
		WHEN customer_feedback = 'very good' THEN '5'
    END AS total_rating
    FROM order_t
)
    
SELECT 
		quarter_number,
    ROUND(AVG(total_rating), 2) AS average_rating
FROM rating
GROUP BY 1 
ORDER BY 1 ASC;

-- Question 5:
-- Find the percentage distribution of feedback from the customers. Are customers getting more dissatisfied over time?

WITH cust_feed AS 
(
	SELECT 
		quarter_number,
		ROUND(SUM(CASE WHEN customer_feedback = 'very good' THEN 1 ELSE 0 END), 2) AS very_good,
		ROUND(SUM(CASE WHEN customer_feedback = 'good' THEN 1 ELSE 0 END), 2) AS good,
		ROUND(SUM(CASE WHEN customer_feedback = 'okay' THEN 1 ELSE 0 END), 2) AS okay,
		ROUND(SUM(CASE WHEN customer_feedback = 'bad' THEN 1 ELSE 0 END), 2) AS bad,
		ROUND(SUM(CASE WHEN customer_feedback = 'very bad' THEN 1 ELSE 0 END), 2) AS very_bad,
		ROUND(COUNT(customer_feedback), 2) AS total_feedback
	FROM order_t
	GROUP BY 1
    ORDER BY 1 ASC
)
   
  SELECT 
		quarter_number,
        ROUND((very_good/total_feedback), 2) AS very_good,
        ROUND((good/total_feedback), 2) AS good,
        ROUND((okay/total_feedback), 2) AS okay,
        ROUND((bad/total_feedback), 2) AS bad,
        ROUND((very_bad/total_feedback), 2) AS very_bad
	FROM cust_feed
	GROUP BY 1
    ORDER BY 1 ASC;


-- Question 6:
-- What is the trend of the number of orders by quarter?

SELECT 
	quarter_number,
	COUNT(order_id) AS total_orders
FROM order_t
GROUP BY 1
ORDER BY 1;


-- Question 7:
-- Calculate the net revenue generated by the company. What is the quarter-over-quarter % change in net revenue?

WITH QoQ AS 
(
	SELECT quarter_number, 
        ROUND(SUM(quantity * (vehicle_price - ((discount/100)*vehicle_price))), 0) AS revenue
	FROM order_t
	GROUP BY quarter_number)
SELECT quarter_number, revenue,
ROUND(LAG(revenue) OVER(ORDER BY quarter_number), 2) AS previous_revenue,
ROUND((revenue - LAG(revenue) OVER(ORDER BY quarter_number))/LAG(revenue) OVER(ORDER BY quarter_number), 2) AS qoq_perc_change
FROM QoQ;

-- Question 8:
-- What is the trend of net revenue and orders by quarters?

SELECT 
	quarter_number,
	ROUND(SUM(quantity*vehicle_price), 0) AS revenue,
    COUNT(order_id) AS total_order
FROM order_t
GROUP BY 1
ORDER BY 1;


-- Question 9:
-- What is the average discount offered for different types of credit cards?

SELECT 
	credit_card_type,
	ROUND(AVG(discount), 2) AS average_discount
FROM order_t t1
INNER JOIN customer_t t2
 ON t1.customer_id = t2.customer_id
GROUP BY 1
ORDER BY 2 DESC;


-- Question 10:
-- What is the average time taken to ship the placed orders for each quarter?

SELECT 
	quarter_number,
    ROUND(AVG(DATEDIFF(ship_date, order_date)), 0) AS average_shipping_time
FROM order_t
GROUP BY 1
ORDER BY 1;

------------------------------------------------------------------------------------

-- Business Overview

-- Total Revenue
SELECT 
    SUM(quantity * vehicle_price) / 1000000 AS revenue_in_millions
FROM order_t;

-- Total orders
SELECT COUNT(DISTINCT shipper_id) AS total_orders
FROM order_t;

-- Total Customers
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customer_t;

-- Average Rating
SELECT 
    AVG(
        CASE LOWER(customer_feedback)
            WHEN 'excellent' THEN 5
            WHEN 'good' THEN 4
            WHEN 'average' THEN 3
            WHEN 'poor' THEN 2
            WHEN 'bad' THEN 1
            ELSE NULL
        END
    ) AS average_rating
FROM order_t;

-- Last Quater revenue
SELECT 
    ROUND(SUM(quantity * vehicle_price) / 1000000, 2) AS fourth_quarter_revenue_millions
FROM order_t
WHERE QUARTER(order_date) = 4;


-- Last Quater orders
SELECT 
    COUNT(quantity * vehicle_price) AS fourth_quarter_order_sum
FROM order_t
WHERE EXTRACT(QUARTER FROM order_date) = 4;

-- Average Days to ship
SELECT 
    AVG(DATEDIFF(ship_date, order_date)) AS avg_days_to_ship
FROM order_t
WHERE ship_date IS NOT NULL;

-- Percentage of Good feedback
SELECT 
    ROUND(
        100.0 * SUM(CASE WHEN LOWER(customer_feedback) = 'good' THEN 1 ELSE 0 END) 
        / COUNT(*), 
        2
    ) AS percentage_good_feedback
FROM order_t
WHERE customer_feedback IS NOT NULL; 
